layout_spectrum: 0.6619256937410682
typography_spectrum: 0.4278790580574423
color:
  brandStrength: 0.7089341727551073
  lightness: 0.005527552217245102
  saturation: 0.7870183563791215
  rhythmicContrast: 0.932849021628499
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
name: Robert-Horne
